// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            HtmlHyperlink uIAboutHyperlink = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UIAboutHyperlink;
            HtmlHyperlink uIContactHyperlink = this.UIHomePageMyASPNETApplWindow.UIAboutMyASPNETApplicaDocument.UIContactHyperlink;
            #endregion

            // Click 'About' link
            Mouse.Click(uIAboutHyperlink, new Point(42, 32));

            // Click 'Contact' link
            Mouse.Click(uIContactHyperlink, new Point(61, 32));
        }
        
        /// <summary>
        /// RecordedMethod2
        /// </summary>
        public void RecordedMethod2()
        {
            #region Variable Declarations
            HtmlHyperlink uIAboutHyperlink = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UIAboutHyperlink;
            HtmlHyperlink uIContactHyperlink = this.UIHomePageMyASPNETApplWindow.UIAboutMyASPNETApplicaDocument.UIContactHyperlink;
            BrowserWindow uIHomePageMyASPNETApplWindow = this.UIHomePageMyASPNETApplWindow;
            #endregion

            // Click 'About' link
            Mouse.Click(uIAboutHyperlink, new Point(47, 28));

            // Click 'Contact' link
            Mouse.Click(uIContactHyperlink, new Point(56, 28));

            // Perform Forward on Browser Window
            uIHomePageMyASPNETApplWindow.Forward();

            // Perform Close on Browser Window
            uIHomePageMyASPNETApplWindow.Close();
        }
        
        /// <summary>
        /// RecordedMethod3 - Use 'RecordedMethod3Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod3()
        {
            #region Variable Declarations
            BrowserWindow uIHomePageMyASPNETApplWindow = this.UIHomePageMyASPNETApplWindow;
            HtmlHyperlink uIAboutHyperlink = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UIAboutHyperlink;
            HtmlHyperlink uIContactHyperlink = this.UIHomePageMyASPNETApplWindow.UIAboutMyASPNETApplicaDocument.UIContactHyperlink;
            #endregion

            // Go to web page 'http://localhost:3339/'
            uIHomePageMyASPNETApplWindow.NavigateToUrl(new System.Uri(this.RecordedMethod3Params.UIHomePageMyASPNETApplWindowUrl));

            // Click 'About' link
            Mouse.Click(uIAboutHyperlink, new Point(44, 29));

            // Click 'Contact' link
            Mouse.Click(uIContactHyperlink, new Point(54, 27));
        }
        
        /// <summary>
        /// RecordedMethod4
        /// </summary>
        public void RecordedMethod4()
        {
            #region Variable Declarations
            HtmlHyperlink uIHomeHyperlink = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UIHomeHyperlink;
            HtmlHyperlink uIAboutHyperlink = this.UIHomePageMyASPNETApplWindow.UIHomePageMyASPNETApplDocument.UIAboutHyperlink;
            HtmlHyperlink uIContactHyperlink = this.UIHomePageMyASPNETApplWindow.UIAboutMyASPNETApplicaDocument.UIContactHyperlink;
            #endregion

            // Click 'Home' link
            Mouse.Click(uIHomeHyperlink, new Point(46, 30));

            // Click 'About' link
            Mouse.Click(uIAboutHyperlink, new Point(39, 24));

            // Click 'Contact' link
            Mouse.Click(uIContactHyperlink, new Point(66, 33));
        }
        
        #region Properties
        public virtual RecordedMethod3Params RecordedMethod3Params
        {
            get
            {
                if ((this.mRecordedMethod3Params == null))
                {
                    this.mRecordedMethod3Params = new RecordedMethod3Params();
                }
                return this.mRecordedMethod3Params;
            }
        }
        
        public UIHomePageMyASPNETApplWindow UIHomePageMyASPNETApplWindow
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplWindow == null))
                {
                    this.mUIHomePageMyASPNETApplWindow = new UIHomePageMyASPNETApplWindow();
                }
                return this.mUIHomePageMyASPNETApplWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod3Params mRecordedMethod3Params;
        
        private UIHomePageMyASPNETApplWindow mUIHomePageMyASPNETApplWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod3'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class RecordedMethod3Params
    {
        
        #region Fields
        /// <summary>
        /// Go to web page 'http://localhost:3339/'
        /// </summary>
        public string UIHomePageMyASPNETApplWindowUrl = "http://localhost:3339/";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageMyASPNETApplWindow : BrowserWindow
    {
        
        public UIHomePageMyASPNETApplWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Home Page - My ASP.NET Application";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            this.WindowTitles.Add("About - My ASP.NET Application");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIHomePageMyASPNETApplDocument UIHomePageMyASPNETApplDocument
        {
            get
            {
                if ((this.mUIHomePageMyASPNETApplDocument == null))
                {
                    this.mUIHomePageMyASPNETApplDocument = new UIHomePageMyASPNETApplDocument(this);
                }
                return this.mUIHomePageMyASPNETApplDocument;
            }
        }
        
        public UIAboutMyASPNETApplicaDocument UIAboutMyASPNETApplicaDocument
        {
            get
            {
                if ((this.mUIAboutMyASPNETApplicaDocument == null))
                {
                    this.mUIAboutMyASPNETApplicaDocument = new UIAboutMyASPNETApplicaDocument(this);
                }
                return this.mUIAboutMyASPNETApplicaDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIHomePageMyASPNETApplDocument mUIHomePageMyASPNETApplDocument;
        
        private UIAboutMyASPNETApplicaDocument mUIAboutMyASPNETApplicaDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIHomePageMyASPNETApplDocument : HtmlDocument
    {
        
        public UIHomePageMyASPNETApplDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Home Page - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3339/";
            this.WindowTitles.Add("Home Page - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIAboutHyperlink
        {
            get
            {
                if ((this.mUIAboutHyperlink == null))
                {
                    this.mUIAboutHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIAboutHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3339/Home/About";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/About\"";
                    this.mUIAboutHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "3";
                    this.mUIAboutHyperlink.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIAboutHyperlink;
            }
        }
        
        public HtmlHyperlink UIHomeHyperlink
        {
            get
            {
                if ((this.mUIHomeHyperlink == null))
                {
                    this.mUIHomeHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIHomeHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Home";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3339/";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/\"";
                    this.mUIHomeHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "2";
                    this.mUIHomeHyperlink.WindowTitles.Add("Home Page - My ASP.NET Application");
                    #endregion
                }
                return this.mUIHomeHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIAboutHyperlink;
        
        private HtmlHyperlink mUIHomeHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAboutMyASPNETApplicaDocument : HtmlDocument
    {
        
        public UIAboutMyASPNETApplicaDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "About - My ASP.NET Application";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/Home/About";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://localhost:3339/Home/About";
            this.WindowTitles.Add("About - My ASP.NET Application");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIContactHyperlink
        {
            get
            {
                if ((this.mUIContactHyperlink == null))
                {
                    this.mUIContactHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIContactHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/Home/Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://localhost:3339/Home/Contact";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/Home/Contact\"";
                    this.mUIContactHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "4";
                    this.mUIContactHyperlink.WindowTitles.Add("About - My ASP.NET Application");
                    #endregion
                }
                return this.mUIContactHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIContactHyperlink;
        #endregion
    }
}
